version: '3'
services:
  mysql:
    image: mysql:8.0.36-debian
    ports:
      - "33061:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: "bluebell"
      MYSQL_PASSWORD: 123456
    volumes:
      - ./init.sql:/data/application/init.sql
  redis:
     image: redis:alpine3.19
     ports:
        - "63791:6379"    
  webblog:
    build: .
    command:  sh -c "./wait-for.sh mysql:3306 redis:6379 -- ./webblog_app ./conf/config.yaml"
    depends_on:
      - mysql
      - redis
    ports:
      - "8888:8081"