name: "WebBlog"
mode: "dev"
version: "v0.0.1"
start_time: "2024-03-01"
machine_id: 1
port: 8081


log:
  level: "debug"
  filename: "WebBlog.log"
  max_size: 200
  max_backups: 7
  max_age: 30

mysql:
    host: mysql 
    port: 3306
    user: "root"
    password: "123456"
    dbname: "bluebell"
    max_open_conns: 200
    max_idle_conns: 50

redis:
    host: redis
    port: 6379
    db: 0
    password: ""
    pool_size: 100